Demo: Display.cpp
	g++ -g -o Display Display.cpp -I/home/firefly/Work/hkVersion/MVS-1.0.0_x86_64/MVS/Samples_LinuxSDK/include -L/home/firefly/Work/hkVersion/MVS-1.0.0_x86_64/MVS/Samples_LinuxSDK/lib/64 -lX11 -lMvCameraControl 
	

clean:
	rm Display -rf
