Demo: GrabMultipleCamera.cpp
	g++ -g -o GrabMultipleCamera GrabMultipleCamera.cpp -I../../include -Wl,-rpath=../../lib -L../../lib -lMvCameraControl -ludev -lpthread
	

clean:
	rm GrabMultipleCamera -rf
