Demo: GrabImage_ROI.cpp
	g++ -g -o GrabImage_ROI GrabImage_ROI.cpp -I/home/firefly/Work/mylibs/opencv/include -I../../include -Wl,-rpath=../../lib -L/home/firefly/Work/mylibs/opencv/lib -L../../lib -lMvCameraControl -lpthread -lopencv_imgproc -lopencv_core -lopencv_highgui
	

clean:
	rm GrabImage_ROI -rf
