Demo: Grab_ImageCallback.cpp
	g++ -g -o Grab_ImageCallback Grab_ImageCallback.cpp -I../../include -Wl,-rpath=../../lib -L../../lib -lMvCameraControl -ludev -lpthread
	

clean:
	rm Grab_ImageCallback -rf
