Demo: GrabImage_ROI.cpp
	g++ -g -o GrabImage_ROI GrabImage_ROI.cpp -I/home/firefly/Work/mylibs/zbar/include/ -I/home/firefly/Work/mylibs/opencv/include -I/home/firefly/Work/hkVersion/SampleSDK_Arm_NvidiaTX/include -Wl,-rpath=/home/firefly/Work/hkVersion/SampleSDK_Arm_NvidiaTX/lib -L/home/firefly/Work/mylibs/opencv/lib -L/home/firefly/Work/hkVersion/SampleSDK_Arm_NvidiaTX/lib -L./ -lMvCameraControl -lpthread -lopencv_imgproc -lopencv_core -lopencv_highgui -l3DInforLib
	

clean:
	rm GrabImage_ROI -rf
